from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from datetime import datetime
import html

# COLORS
COL_NAVY = colors.HexColor("#002B5B")
COL_SLATE = colors.HexColor("#2B4C7E")
COL_RED = colors.HexColor("#D32F2F")
COL_ORANGE = colors.HexColor("#F57C00")
COL_GREEN = colors.HexColor("#388E3C")
COL_GREY_BG = colors.HexColor("#F0F0F0")

def draw_header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(COL_NAVY)
    canvas.rect(0, letter[1]-40, letter[0], 40, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(40, letter[1]-25, "VAPT EXECUTIVE REPORT")
    canvas.drawRightString(letter[0]-40, letter[1]-25, "CONFIDENTIAL")
    
    # Footer
    canvas.setFillColor(colors.black)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(40, 20, f"Page {doc.page} | Generated by GVhacks DomainEnum")
    canvas.drawRightString(letter[0]-40, 20, datetime.now().strftime('%Y-%m-%d %H:%M'))
    canvas.restoreState()

def draw_cover(canvas, doc, domain):
    """
    Draws the cover page on the canvas.
    Note: This draws on absolute page coordinates (0,0 is bottom-left).
    """
    canvas.saveState()
    w, h = letter
    
    # 1. Background Split (Professional Two-Tone)
    # Top 60% Navy Blue
    canvas.setFillColor(COL_NAVY)
    canvas.rect(0, h * 0.4, w, h * 0.6, fill=1, stroke=0)
    
    # 2. VAPT Shield Icon (Vector Drawing)
    canvas.saveState()
    canvas.translate(w/2, h * 0.78) # Position near top center
    canvas.setStrokeColor(colors.white)
    canvas.setLineWidth(3)
    
    # Draw Shield Path
    p = canvas.beginPath()
    p.moveTo(0, 0)       # Center top of shield body
    p.lineTo(50, 20)     # Top Right corner
    p.lineTo(50, -40)    # Right side down
    p.curveTo(50, -100, 0, -130, 0, -130) # Curve to bottom tip
    p.curveTo(0, -130, -50, -100, -50, -40) # Curve up left
    p.lineTo(-50, 20)    # Left side up
    p.lineTo(0, 0)       # Close loop
    canvas.drawPath(p, fill=0, stroke=1)
    
    # Draw Inner "Checkmark" (Symbolizing Scan Complete)
    canvas.setStrokeColor(COL_ORANGE)
    canvas.setLineWidth(5)
    canvas.line(-20, -50, -5, -70)
    canvas.line(-5, -70, 25, -30)
    canvas.restoreState()

    # 3. Report Title (Centered White Text)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 36)
    canvas.drawCentredString(w/2, h * 0.60, "VULNERABILITY")
    canvas.drawCentredString(w/2, h * 0.55, "ASSESSMENT REPORT")
    
    # 4. Target & Date (Centered White Text)
    canvas.setFont("Helvetica", 14)
    canvas.setFillColor(colors.HexColor("#E0E0E0")) # Off-white
    canvas.drawCentredString(w/2, h * 0.48, f"TARGET SCOPE: {domain}")
    canvas.drawCentredString(w/2, h * 0.45, f"DATE: {datetime.now().strftime('%B %d, %Y')}")
    
    # 5. Orange Accent Divider
    canvas.setStrokeColor(COL_ORANGE)
    canvas.setLineWidth(6)
    canvas.line(0, h * 0.4, w, h * 0.4)

    # 6. Branding (Bottom White Section)
    canvas.setFillColor(COL_NAVY)
    canvas.setFont("Helvetica-Bold", 48)
    canvas.drawCentredString(w/2, h * 0.25, "GV hacks")
    
    canvas.setFillColor(COL_SLATE)
    canvas.setFont("Helvetica", 16)
    canvas.drawCentredString(w/2, h * 0.20, "Automated Security Reconnaissance")

    # 7. Confidential Stamp (Top Right)
    canvas.saveState()
    canvas.translate(w - 90, h - 50)
    canvas.setFillColor(COL_RED)
    canvas.setStrokeColor(COL_RED)
    canvas.setLineWidth(2)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawCentredString(0, -4, "CONFIDENTIAL")
    canvas.roundRect(-55, -12, 110, 24, 6, stroke=1, fill=0)
    canvas.restoreState()
    
    # 8. Disclaimer Footer
    canvas.setFillColor(colors.grey)
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(w/2, 40, "This document contains confidential security findings.")
    canvas.drawCentredString(w/2, 30, "Unauthorized distribution is strictly prohibited.")

    canvas.restoreState()

def kpi_card(title, val, color):
    t_style = TableStyle([
        ('BOX', (0,0), (-1,-1), 1.5, color),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BACKGROUND', (0,0), (-1,-1), colors.white)
    ])
    val = html.escape(str(val))
    content = f'''<para align="center"><font size="10" color="grey">{title}</font><br/><br/><font size="16" color="{color.hexval()}"><b>{val}</b></font></para>'''
    t = Table([[Paragraph(content)]], colWidths=[130], rowHeights=[70])
    t.setStyle(t_style)
    return t

def generate_pdf_report(domain, data, filename):
    doc = SimpleDocTemplate(filename, pagesize=letter, topMargin=50, bottomMargin=50)
    story = []
    styles = getSampleStyleSheet()
    
    # --- FIX FOR COVER PAGE ---
    # We add a PageBreak at the start.
    # We instruct doc.build to draw the cover on the 'FirstPage' (which is the one before the break effectively, or the first physical page).
    # SimpleDocTemplate will generate Page 1, run 'onFirstPage', and since we added PageBreak, move to Page 2 for content.
    story.append(PageBreak())
    
    # STYLES
    h1 = ParagraphStyle('H1', parent=styles['Heading1'], textColor=COL_NAVY, fontSize=18, spaceAfter=12, spaceBefore=12)
    h2 = ParagraphStyle('H2', parent=styles['Heading2'], textColor=COL_SLATE, fontSize=14, spaceAfter=8, spaceBefore=10)
    
    # Normal style for paragraphs
    norm = ParagraphStyle('Norm', parent=styles['Normal'], fontSize=10, leading=12)
    
    # Table Content Styles (Essential for wrapping)
    tbl_header = ParagraphStyle('TblHead', parent=styles['Normal'], fontSize=10, fontName='Helvetica-Bold', textColor=colors.white)
    tbl_body = ParagraphStyle('TblBody', parent=styles['Normal'], fontSize=9, leading=11, textColor=colors.black)
    
    small = ParagraphStyle('Small', parent=styles['Normal'], fontSize=8, leading=10)

    # --- 1. EXECUTIVE SUMMARY ---
    story.append(Paragraph("Executive Summary", h1))
    
    open_p = len(data.get('ports', {}).get('open_ports', []))
    waf = "YES" if "No WAF" not in data.get('waf', 'No WAF') else "NO"
    gql = "YES" if data.get('graphql') else "NO"
    ip_acc = "YES" if data.get('ip_accessible', {}).get('accessible') else "NO"
    
    kpis = [
        kpi_card("Open Ports", str(open_p), COL_SLATE),
        kpi_card("WAF Active", waf, COL_GREEN if waf=="YES" else COL_RED),
        kpi_card("GraphQL", gql, COL_RED if gql=="YES" else COL_GREEN),
        kpi_card("IP Accessible", ip_acc, COL_ORANGE if ip_acc=="YES" else COL_GREEN)
    ]
    # Use Table for layout of cards
    story.append(Table([kpis], colWidths=[140]*4, hAlign='CENTER'))
    story.append(Spacer(1, 20))
    
    # --- 2. RISK OVERVIEW (CHARTS) ---
    story.append(Paragraph("Risk Overview", h1))
    
    # Logic for Charts
    crit = 0
    if data.get('secrets'): crit += 1
    if data.get('host_injection', {}).get('vulnerable'): crit += 1
    
    warn = 0
    if gql == "YES": warn += 1
    if ip_acc == "YES": warn += 1
    if data.get('headers', {}).get('missing'): warn += 1
    if len(data.get('broken_links', [])) > 0: warn += 1
    
    safe = 1 # Baseline
    if waf == "YES": safe += 1
    if data.get('ssl', {}).get('valid'): safe += 1
    
    # Pie Chart
    d = Drawing(200, 120)
    pc = Pie()
    pc.x = 50
    pc.y = 10
    pc.width = 100
    pc.height = 100
    pc.data = [crit, warn, safe]
    pc.labels = [f'Critical ({crit})', f'Warning ({warn})', f'Safe ({safe})']
    pc.simpleLabels = 0
    pc.slices[0].fillColor = COL_RED
    pc.slices[1].fillColor = COL_ORANGE
    pc.slices[2].fillColor = COL_GREEN
    d.add(pc)
    
    # Bar Chart
    bc_data = [open_p, len(data.get('js_files', [])), len(data.get('emails', []))]
    d2 = Drawing(200, 120)
    bc = VerticalBarChart()
    bc.x = 20
    bc.y = 20
    bc.width = 150
    bc.height = 80
    bc.data = [bc_data]
    bc.categoryAxis.categoryNames = ['Ports', 'JS Files', 'Emails']
    bc.bars[0].fillColor = COL_SLATE
    bc.valueAxis.valueMin = 0
    bc.valueAxis.valueMax = max(bc_data) + 2 if bc_data else 5
    d2.add(bc)
    
    # Layout Charts
    chart_table = Table([[d, d2], ["Risk Distribution", "Recon Counts"]], colWidths=[250, 250])
    chart_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,1), (-1,1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,1), (-1,1), COL_SLATE)
    ]))
    story.append(chart_table)
    story.append(Spacer(1, 20))
    
    # --- 3. INFRASTRUCTURE FINDINGS ---
    story.append(Paragraph("Infrastructure Findings", h1))
    
    # Server Info Table - USING PARAGRAPHS FOR WRAPPING
    s_info = data.get('server_info', {})
    
    # Prepare rows with Paragraphs
    info_rows = []
    raw_info = [
        ["IP Address", data['dns'].get('ip', 'N/A')],
        ["Server Header", s_info.get('server_header', 'N/A')],
        ["Technology", s_info.get('x_powered_by', 'N/A')],
        ["CMS", data.get('cms', 'Unknown')],
        ["SSL Issuer", data.get('ssl', {}).get('issuer', 'N/A')]
    ]
    
    for key, val in raw_info:
        # Wrap content in Paragraph to ensure text wrap
        info_rows.append([
            Paragraph(key, tbl_body),
            Paragraph(html.escape(str(val)), tbl_body)
        ])
    
    # Header Row
    header = [Paragraph("Attribute", tbl_header), Paragraph("Value", tbl_header)]
    
    t1 = Table([header] + info_rows, colWidths=[150, 350])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COL_SLATE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [COL_GREY_BG, colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(t1)
    story.append(Spacer(1, 15))
    
    # Ports Table
    if open_p > 0:
        story.append(Paragraph(f"Open Ports ({len(data['ports']['open_ports'])})", h2))
        
        p_rows = []
        for p in data['ports']['open_ports']:
            details = p.get('version', '')
            if p.get('vuln_info'): details += f" | {p['vuln_info']}"
            
            p_rows.append([
                Paragraph(str(p['port']), tbl_body),
                Paragraph(p['service'], tbl_body),
                Paragraph(html.escape(details), tbl_body)
            ])
            
        p_header = [Paragraph("Port", tbl_header), Paragraph("Service", tbl_header), Paragraph("Version / Details", tbl_header)]
            
        t2 = Table([p_header] + p_rows, colWidths=[60, 100, 340])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), COL_SLATE),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(t2)
    else:
        story.append(Paragraph("No open ports found.", norm))
    
    story.append(Spacer(1, 20))

    # --- 4. VULNERABILITY ANALYSIS ---
    story.append(Paragraph("Vulnerability Analysis", h1))
    
    # Host Injection
    hi = data.get('host_injection', {})
    if hi.get('vulnerable'):
        story.append(Paragraph("<b>CRITICAL: Host Header Injection Detected</b>", h2))
        story.append(Paragraph(f"<font color='red'>{html.escape(hi['details'])}</font>", norm))
    else:
        story.append(Paragraph("<b>Host Header Injection:</b> <font color='green'>Safe</font>", norm))
    
    story.append(Spacer(1, 10))
    
    # Security Headers
    missing_h = data.get('headers', {}).get('missing', [])
    if missing_h:
        story.append(Paragraph(f"<b>Missing Security Headers ({len(missing_h)})</b>", h2))
        h_data = []
        for i in range(0, len(missing_h), 2):
            col1 = Paragraph(missing_h[i], ParagraphStyle('RedText', parent=tbl_body, textColor=COL_RED))
            col2 = ""
            if i+1 < len(missing_h): 
                col2 = Paragraph(missing_h[i+1], ParagraphStyle('RedText', parent=tbl_body, textColor=COL_RED))
            h_data.append([col1, col2])
        
        t_head = Table(h_data, colWidths=[250, 250])
        story.append(t_head)
    else:
        story.append(Paragraph("<b>Security Headers:</b> <font color='green'>All core headers present.</font>", norm))

    # GraphQL
    if data.get('graphql'):
        story.append(Spacer(1, 10))
        story.append(Paragraph("<b>Exposed GraphQL Endpoints</b>", h2))
        for g in data['graphql']:
            story.append(Paragraph(f"- {html.escape(g)}", norm))

    story.append(Spacer(1, 20))

    # --- 5. RECONNAISSANCE FINDINGS ---
    story.append(Paragraph("Reconnaissance Findings", h1))
    
    # JS Files
    js_files = data.get('js_files', [])
    story.append(Paragraph(f"<b>JavaScript Files ({len(js_files)})</b>", h2))
    if js_files:
        path = html.escape(data.get('js_save_path', 'Not saved'))
        story.append(Paragraph(f"Files saved locally to: <i>{path}</i>", small))
        story.append(Spacer(1, 5))
        
        for js in js_files[:15]:
            # CLEANUP: Remove HTML junk if present (e.g., "><script...")
            clean_js = str(js)
            if '"' in clean_js: clean_js = clean_js.split('"')[0]
            if '<' in clean_js: clean_js = clean_js.split('<')[0]
            if '>' in clean_js: clean_js = clean_js.split('>')[0]
            
            story.append(Paragraph(f"- {html.escape(clean_js.strip())}", small))
            
        if len(js_files) > 15:
            story.append(Paragraph(f"... and {len(js_files)-15} more.", small))
    else:
        story.append(Paragraph("No JavaScript files found.", norm))
    
    story.append(Spacer(1, 10))
    
    # Emails
    emails = data.get('emails', [])
    if emails:
        story.append(Paragraph(f"<b>Extracted Emails ({len(emails)})</b>", h2))
        for e in emails:
            story.append(Paragraph(f"- {html.escape(e)}", norm))
    
    story.append(Spacer(1, 10))
    
    # Secrets
    secrets = data.get('secrets', [])
    if secrets:
        story.append(Paragraph(f"<b>Potential Secrets / Keys ({len(secrets)})</b>", h2))
        sec_rows = []
        for s in secrets:
            sec_rows.append([
                Paragraph(s['type'], tbl_body),
                Paragraph(html.escape(s['snippet']), tbl_body),
                Paragraph(html.escape(s['source'].split('/')[-1]), tbl_body)
            ])
            
        sec_header = [Paragraph("Type", tbl_header), Paragraph("Snippet", tbl_header), Paragraph("Source", tbl_header)]
            
        t_sec = Table([sec_header] + sec_rows, colWidths=[100, 250, 150])
        t_sec.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), COL_RED),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 4),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(t_sec)
    else:
        story.append(Paragraph("No high-confidence secrets detected.", norm))

    story.append(Spacer(1, 30))

    # --- 6. DISCLAIMER ---
    story.append(Paragraph("Legal Disclaimer", h2))
    disclaimer = """This report was generated by GVhacks DomainEnum for educational and authorized security assessment purposes only. 
    The information contained herein is confidential. The user is responsible for ensuring scanning activities comply with local laws and organizational policies."""
    
    t_disc = Table([[Paragraph(disclaimer, norm)]], colWidths=[500])
    t_disc.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.grey),
        ('BACKGROUND', (0,0), (-1,-1), COL_GREY_BG),
        ('PADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(t_disc)

    # Build PDF
    # Passing the draw_cover to onFirstPage allows us to paint the background
    doc.build(story, 
              onFirstPage=lambda c, d: draw_cover(c, d, domain), 
              onLaterPages=draw_header_footer)