from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing, Rect
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.legends import Legend
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from datetime import datetime
import html

# --- COLOR PALETTE ---
COL_PRIMARY = colors.HexColor("#002B5B")  # Dark Navy (Executive)
COL_SECONDARY = colors.HexColor("#2B4C7E") # Slate Blue
COL_ACCENT = colors.HexColor("#567EBB")    # Lighter Blue
COL_BG_HEADER = colors.HexColor("#F0F4F8") # Light Grey/Blue for headers
COL_BG_CARD = colors.HexColor("#FFFFFF")   # White for cards
COL_TEXT_DARK = colors.HexColor("#333333")
COL_CRITICAL = colors.HexColor("#D32F2F")  # Red
COL_WARN = colors.HexColor("#F57C00")      # Orange
COL_SAFE = colors.HexColor("#388E3C")      # Green
COL_INFO = colors.HexColor("#1976D2")      # Blue

def draw_header_footer(canvas, doc):
    """Draws the header and footer on every page (except cover)."""
    canvas.saveState()
    
    # Header
    canvas.setFillColor(COL_PRIMARY)
    canvas.rect(0, letter[1] - 40, letter[0], 40, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(40, letter[1] - 25, "VULNERABILITY ASSESSMENT REPORT")
    canvas.drawRightString(letter[0] - 40, letter[1] - 25, "CONFIDENTIAL")
    
    # Footer
    canvas.setStrokeColor(colors.lightgrey)
    canvas.line(40, 40, letter[0] - 40, 40)
    canvas.setFillColor(colors.grey)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(40, 25, f"Generated by GVhacks DomainEnum | {datetime.now().strftime('%Y-%m-%d')}")
    canvas.drawRightString(letter[0] - 40, 25, f"Page {doc.page}")
    
    canvas.restoreState()

def draw_cover_page(canvas, doc, domain):
    """Draws a professional full-page cover."""
    canvas.saveState()
    width, height = letter
    
    # Background Sidebar
    canvas.setFillColor(COL_PRIMARY)
    canvas.rect(0, 0, width * 0.35, height, fill=1, stroke=0)
    
    # Decorative Accent
    canvas.setFillColor(COL_SECONDARY)
    canvas.rect(width * 0.35, 0, 10, height, fill=1, stroke=0)
    
    # Title Section (Right Side)
    canvas.setFillColor(COL_PRIMARY)
    canvas.setFont("Helvetica-Bold", 36)
    canvas.drawString(width * 0.42, height * 0.75, "Vulnerability")
    canvas.drawString(width * 0.42, height * 0.75 - 40, "Assessment")
    canvas.setFillColor(COL_ACCENT)
    canvas.drawString(width * 0.42, height * 0.75 - 80, "Report")
    
    # Target Info
    canvas.setFillColor(colors.black)
    canvas.setFont("Helvetica", 14)
    canvas.drawString(width * 0.42, height * 0.55, "TARGET DOMAIN")
    canvas.setFont("Helvetica-Bold", 20)
    canvas.setFillColor(COL_SECONDARY)
    canvas.drawString(width * 0.42, height * 0.55 - 25, domain)
    
    # Date
    canvas.setFillColor(colors.black)
    canvas.setFont("Helvetica", 12)
    canvas.drawString(width * 0.42, height * 0.45, f"Scan Date: {datetime.now().strftime('%B %d, %Y')}")
    
    # Branding (Left Sidebar)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 28)
    # Rotating text for artistic effect or standard placement
    canvas.drawString(30, height - 100, "GV")
    canvas.setFont("Helvetica", 28)
    canvas.drawString(30, height - 130, "hacks")
    
    canvas.setFont("Helvetica", 10)
    canvas.drawString(30, 50, "Automated Reconnaissance Tool")
    canvas.drawString(30, 38, "v2.0 Enterprise Edition")
    
    canvas.restoreState()

def create_kpi_card(title, value, color):
    """Creates a small table acting as a KPI card."""
    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.white),
        ('BOX', (0, 0), (-1, -1), 1, color),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ])
    
    # HTML styling for text inside the card
    text = f'''<para align="center">
    <font size="10" color="grey">{title}</font><br/>
    <font size="16" color="{color.hexval()}"><b>{value}</b></font>
    </para>'''
    
    t = Table([[Paragraph(text)]], colWidths=[120], rowHeights=[60])
    t.setStyle(style)
    return t

def generate_pdf_report(domain, data, filename):
    doc = SimpleDocTemplate(filename, pagesize=letter, topMargin=60, bottomMargin=60)
    story = []
    styles = getSampleStyleSheet()
    
    # --- STYLES ---
    style_h1 = ParagraphStyle('Header1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=18, textColor=COL_PRIMARY, spaceAfter=12, spaceBefore=20)
    style_h2 = ParagraphStyle('Header2', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=14, textColor=COL_SECONDARY, spaceAfter=10, spaceBefore=15)
    style_normal = ParagraphStyle('NormalText', parent=styles['Normal'], fontSize=10, leading=14, textColor=COL_TEXT_DARK)
    style_card_title = ParagraphStyle('CardTitle', parent=styles['Normal'], fontSize=12, fontName='Helvetica-Bold', textColor=COL_PRIMARY)

    # --- 1. COVER PAGE ---
    # We define a special flowable just to trigger the cover page drawing
    class Cover(Spacer):
        def wrap(self, availWidth, availHeight):
            return (0, 0)
        def draw(self):
            draw_cover_page(self.canv, doc, domain)
            
    story.append(Cover(1, 1))
    story.append(PageBreak())

    # --- 2. EXECUTIVE SUMMARY & KPI ---
    story.append(Paragraph("Executive Summary", style_h1))
    
    # Calculate KPI Data
    open_ports_count = len(data.get('ports', {}).get('open_ports', []))
    waf_status = "DETECTED" if "No WAF" not in data.get('waf', 'No WAF') else "NONE"
    waf_color = COL_SAFE if waf_status == "DETECTED" else COL_WARN
    
    graphql_exposed = "YES" if data.get('graphql') else "NO"
    graphql_color = COL_WARN if graphql_exposed == "YES" else COL_SAFE
    
    ip_acc = "YES" if data.get('ip_accessible', {}).get('accessible') else "NO"
    ip_color = COL_WARN if ip_acc == "YES" else COL_SAFE

    # KPI Table
    kpi_row = [
        create_kpi_card("Open Ports", str(open_ports_count), COL_INFO),
        create_kpi_card("WAF Status", waf_status, waf_color),
        create_kpi_card("GraphQL", graphql_exposed, graphql_color),
        create_kpi_card("IP Access", ip_acc, ip_color)
    ]
    
    t_kpi = Table([kpi_row], colWidths=[130]*4)
    t_kpi.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(t_kpi)
    story.append(Spacer(1, 20))
    
    story.append(Paragraph(f"This report details the security posture of <b>{domain}</b>. The assessment was conducted using passive reconnaissance and active non-intrusive scanning techniques. The following sections provide a breakdown of discovered assets, services, and potential vulnerabilities.", style_normal))
    story.append(Spacer(1, 20))

    # --- 3. RISK OVERVIEW (CHARTS) ---
    story.append(Paragraph("Risk Overview", style_h1))
    
    # Risk Logic
    crit_count = 0
    warn_count = 0
    safe_count = 0
    
    # Calc Critical
    if data.get('host_injection', {}).get('vulnerable'): crit_count += 1
    if len(data.get('secrets', [])) > 0: crit_count += 1
    
    # Calc Warn
    if data.get('graphql'): warn_count += 1
    if data.get('headers', {}).get('missing'): warn_count += 1
    if ip_acc == "YES": warn_count += 1
    if len(data.get('broken_links', [])) > 0: warn_count += 1
    
    # Calc Safe (Arbitrary baseline + good configs)
    if waf_status == "DETECTED": safe_count += 1
    if data.get('ssl', {}).get('valid'): safe_count += 1
    if not data.get('host_injection', {}).get('vulnerable'): safe_count += 1
    
    # Avoid empty chart
    if crit_count == 0 and warn_count == 0 and safe_count == 0:
        safe_count = 1

    # --- PIE CHART (Risk Distribution) ---
    d_pie = Drawing(200, 100)
    pc = Pie()
    pc.x = 50
    pc.y = 0
    pc.width = 100
    pc.height = 100
    pc.data = [crit_count, warn_count, safe_count]
    pc.labels = [f"Critical ({crit_count})", f"Warning ({warn_count})", f"Safe ({safe_count})"]
    pc.simpleLabels = 0
    
    # Colors mapping
    pc.slices[0].fillColor = COL_CRITICAL
    pc.slices[1].fillColor = COL_WARN
    pc.slices[2].fillColor = COL_SAFE
    d_pie.add(pc)
    
    # --- BAR CHART (Findings by Category) ---
    # Categories: Network (Ports), Web (Headers, CMS, Robots), Content (JS, Emails)
    cat_net = open_ports_count
    cat_web = len(data.get('headers', {}).get('missing', [])) + (1 if data.get('cms') else 0)
    cat_content = len(data.get('js_files', [])) + len(data.get('emails', []))
    
    d_bar = Drawing(200, 100)
    bc = VerticalBarChart()
    bc.x = 20
    bc.y = 0
    bc.height = 100
    bc.width = 150
    bc.data = [[cat_net, cat_web, cat_content]]
    bc.categoryAxis.categoryNames = ['Network', 'Web Config', 'Content']
    bc.bars[0].fillColor = COL_SECONDARY
    d_bar.add(bc)

    # Place charts side-by-side
    chart_table = Table([[d_pie, d_bar], ["Risk Distribution", "Findings by Category"]], colWidths=[250, 250])
    chart_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,1), (-1,1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,1), (-1,1), COL_SECONDARY),
    ]))
    story.append(chart_table)
    story.append(Spacer(1, 30))

    # --- 4. SERVER & NETWORK FINDINGS ---
    story.append(Paragraph("Server & Network Findings", style_h1))
    
    # Server Info Table
    s_info = data.get('server_info', {})
    server_data = [
        ["Parameter", "Status/Value"],
        ["IP Address", data['dns'].get('ip')],
        ["Server Header", html.escape(s_info.get('server_header', 'N/A'))],
        ["Technology", html.escape(s_info.get('x_powered_by', 'N/A'))],
        ["CMS Detected", html.escape(data.get('cms', 'Unknown'))],
        ["SSL Issuer", html.escape(data.get('ssl', {}).get('issuer', 'N/A'))],
    ]
    
    t_server = Table(server_data, colWidths=[150, 350])
    t_server.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COL_SECONDARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [COL_BG_HEADER, colors.white]), # Zebra
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t_server)
    story.append(Spacer(1, 15))
    
    # Open Ports Table
    story.append(Paragraph("Open Ports", style_h2))
    if 'open_ports' in data['ports'] and data['ports']['open_ports']:
        port_rows = [["Port", "Service", "Version / Details"]]
        for p in data['ports']['open_ports']:
            details = p.get('version', '')
            if p.get('vuln_info'): details += f" | {p['vuln_info']}"
            port_rows.append([str(p['port']), p['service'], html.escape(details[:80])])
            
        t_ports = Table(port_rows, colWidths=[60, 100, 340])
        t_ports.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), COL_ACCENT),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        story.append(t_ports)
    else:
        story.append(Paragraph("No open ports found.", style_normal))
        
    story.append(Spacer(1, 20))

    # --- 5. VULNERABILITY ANALYSIS ---
    story.append(Paragraph("Vulnerability Analysis", style_h1))
    
    # Host Injection
    hi = data.get('host_injection', {})
    if hi.get('vulnerable'):
        story.append(Paragraph("<b>CRITICAL: Host Header Injection Detected</b>", style_h2))
        story.append(Paragraph(f"<font color='red'>{html.escape(hi['details'])}</font>", style_normal))
    else:
        story.append(Paragraph("<b>Host Header Injection:</b> <font color='green'>Safe</font>", style_normal))
    
    story.append(Spacer(1, 10))
    
    # Security Headers
    story.append(Paragraph("Missing Security Headers", style_h2))
    missing_h = data.get('headers', {}).get('missing', [])
    if missing_h:
        # 2-column list for headers to save space
        h_data = []
        for i in range(0, len(missing_h), 2):
            row = [missing_h[i]]
            if i+1 < len(missing_h): row.append(missing_h[i+1])
            else: row.append("")
            h_data.append(row)
            
        t_head = Table(h_data, colWidths=[250, 250])
        t_head.setStyle(TableStyle([
            ('TEXTCOLOR', (0,0), (-1,-1), COL_CRITICAL),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Oblique'),
        ]))
        story.append(t_head)
    else:
        story.append(Paragraph("<font color='green'>All core headers present.</font>", style_normal))

    # GraphQL
    if data.get('graphql'):
        story.append(Spacer(1, 10))
        story.append(Paragraph("Exposed GraphQL Endpoints", style_h2))
        for g in data['graphql']:
            story.append(Paragraph(f"- {html.escape(g)}", style_normal))

    story.append(Spacer(1, 20))

    # --- 6. JS & RECON FINDINGS ---
    story.append(Paragraph("JavaScript & Recon Findings", style_h1))
    
    # JS Files
    js_count = len(data.get('js_files', []))
    story.append(Paragraph(f"<b>JavaScript Analysis:</b> {js_count} files identified and saved.", style_normal))
    
    # Secrets
    secrets = data.get('secrets', [])
    if secrets:
        story.append(Paragraph("<b>Potential Secrets Found (Verify Manually):</b>", style_h2))
        sec_rows = [["Type", "Snippet", "Source"]]
        for s in secrets:
            sec_rows.append([s['type'], html.escape(s['snippet']), html.escape(s['source'].split('/')[-1])])
            
        t_sec = Table(sec_rows, colWidths=[100, 250, 150])
        t_sec.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), COL_CRITICAL),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(t_sec)
    else:
        story.append(Paragraph("No API keys or secrets detected in static analysis.", style_normal))
        
    story.append(Spacer(1, 30))

    # --- 7. DISCLAIMER ---
    story.append(Paragraph("Legal Disclaimer", style_h2))
    disclaimer = """This report was generated by GVhacks DomainEnum for authorized security assessment purposes only. 
    The information contained herein is confidential. The user is responsible for ensuring scanning activities comply with local laws and organizational policies."""
    
    t_disc = Table([[Paragraph(disclaimer, style_normal)]], colWidths=[500])
    t_disc.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.grey),
        ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
        ('PADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(t_disc)

    # Build PDF
    # We use 'onLaterPages' for the header/footer on pages 2+
    doc.build(story, onFirstPage=lambda c, d: None, onLaterPages=draw_header_footer)